name: Weather APP CI
on: 
  push:
    branches: main
  pull_request:
jobs:
  ci:
   runs-on: ubuntu-latest
   steps:
     - name: Get the code
       uses: actions/checkout@v4
     - name: setup Node enviroment
       uses: actions/setup-node@v6.0.0
     - name: Install Dependencies
       run: yarn install
     - name: run linting
       run: yarn lint
     - name: Run Tests
       run: yarn test --watchAll=false
     - name: Build Project 
       run : yarn build
     - name: Setup Docker
       uses: docker/setup-buildx-action@v3.11.1
     - name: Login to docker hub
       uses: docker/login-action@v3.6.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secretsDOCKER_TOKEN }}
     - name: Build and Push docker image
       uses: docker/build-push-action@v6.18.0
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/weather-app-cicd:latest
      
       
    
